# Generated by Django 4.2.3 on 2023-08-03 22:56

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.upload_img),
            preserve_default=False,
        ),
    ]
